# Конфигурационный файл для плагина SnowballFight
# Настройки эффектов снежка
snowball_effects:
  slowness:
    duration: 3  # длительность в секундах (будет конвертироваться в тики, 20 тиков = 1 секунда)
    amplifier: 4  # сила эффекта (уровень 5, так как начинается с 0)

# Настройки кулдауна снежка
snowball_cooldown:
  enabled: true  # включить/выключить кулдаун
  duration: 2  # длительность кулдауна в секундах

# Настройки звука при попадании снежка
snowball_sound:
  enabled: true # включить/выключить звук
  sound_type: "minecraft:entity.firework_rocket.blast"  # тип звука при попадании снежка

# Настройки партиклов
particle_effects:
  multiplier: 1  # множитель количества партиклов (1 = стандартное количество, 2 = в 2 раза больше и т.д.)